name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Version
      run: echo "VERSION=$(sed ':a; N; s/[[:space:]]//g; ta' VERSION)" >> $GITHUB_ENV
    - name: Prepare Release File Folder
      run: mkdir -p build/release
    - name: Create DEB Package
      run: |
        mkdir -p build/deb
        mkdir -p build/deb2
        mkdir -p build/release
        mkdir -p build/release2
        docker build packaging/deb -t create_deb_package
        docker run -v $PWD:/rescreen -v  $PWD/build/deb:/build create_deb_package -v ${{ env.VERSION }} -i /rescreen -o /build
        cp build/deb/*.deb build/release
        ls -la build/release

        docker run -v $PWD:/rescreen -v  $PWD/build/deb2:/build --user $UID create_deb_package -v ${{ env.VERSION }} -i /rescreen -o /build
        cp build/deb2/*.deb build/release2
        ls -la build/release2

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/release2/*