name: Write Version to File
on:
  push:
    branches:
      - main

jobs:
  version-to-file:
    runs-on: ubuntu-latest
    name: Write Version to File
    steps:
    - uses: actions/checkout@v3
    - name: Update version
      uses: brettdorrans/write-version-to-file@master
      with:
        filename: '.VERSION'
